version: 2
updates:
- package-ecosystem: cargo
  directory: '/'
  schedule:
    interval: monthly
  allow:
  - dependency-type: all
  groups:
    cargo:
      patterns: ['*']

- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: monthly
  groups:
    github-actions:
      patterns: ['*']
