[package]
name = "cargo-smart-release"
version = "0.21.7"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
repository = "https://github.com/GitoxideLabs/cargo-smart-release"
description = "Cargo subcommand for fearlessly releasing crates in workspaces."
license = "MIT OR Apache-2.0"
edition = "2021"
categories = ["development-tools::cargo-plugins"]
keywords = ["cargo"]
include = ["src/**/*", "README.md", "CHANGELOG.md"]

[[bin]]
name = "cargo-smart-release"
path = "src/cli/main-smart-release.rs"
test = false

[[bin]]
name = "cargo-changelog"
path = "src/cli/main-changelog.rs"
test = false
[features]
cache-efficiency-debug = ["gix/cache-efficiency-debug"]

[dependencies]
gix = { version = "0.73.0", default-features = false, features = ["max-performance", "interrupt"] }
anyhow = "1.0.42"
clap = { version = "4.5.42", features = ["derive", "cargo"] }
env_logger = { version = "0.11.6", default-features = false, features = ["humantime", "auto-color"] }
cargo_metadata = "0.21.0"
log = "0.4.14"
toml_edit = "0.23.2"
semver = "1.0.4"
crates-index = { version = "3.11.0", default-features = false, features = ["git-performance", "git-https"] }
cargo_toml = "0.22.3"
winnow = "0.7.12"
git-conventional = "0.12.0"
jiff = "0.2.15"
pulldown-cmark = { version = "0.9.6", default-features = false }
bitflags = "2"

[dev-dependencies]
insta = "1.43.1"
gix-testtools = "0.16.1"
testing_logger = "0.1.1"

[workspace]
